.TH "NonlinearModel" 3 "Version 1.6" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NonlinearModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMathModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNonlinearModel\fP (double a, double b, double c, double d)"
.br
.RI "Конструктор нелинейной модели "
.ti -1c
.RI "double \fBcalculateOutput\fP (double Yt, double Yt_1, double U) override"
.br
.RI "Расчет выходного значения модели "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NonlinearModel::NonlinearModel (double a, double b, double c, double d)\fC [inline]\fP"

.PP
Конструктор нелинейной модели 
.PP
\fBParameters\fP
.RS 4
\fIa\fP Параметр a 
.br
\fIb\fP Параметр b 
.br
\fIc\fP Параметр c 
.br
\fId\fP Параметр d 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double NonlinearModel::calculateOutput (double Yt, double Yt_1, double U)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Расчет выходного значения модели 
.PP
\fBParameters\fP
.RS 4
\fIYt\fP Текущее значение 
.br
\fIYt_1\fP Предыдущее значение 
.br
\fIU\fP Входное значение 
.RE
.PP
\fBReturns\fP
.RS 4
Выходное значение модели 
.RE
.PP

.PP
Implements \fBMathModel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
